/// Предустановленные жанры для выбора чипами в студии.
const List<String> studioGenreOptions = [
  'Pop',
  'Rock',
  'Electronic',
  'Hip-Hop',
  'R&B',
  'Jazz',
  'Classical',
  'Ambient',
  'Lo-Fi',
  'Metal',
  'Punk',
  'Indie',
  'Folk',
  'Country',
  'Reggae',
  'Drum & Bass',
  'House',
  'Techno',
  'Trance',
  'Dubstep',
  'Other',
];
